### ISSUE TITLE
SoftBank UltraLink

### ISSUE THREAD

**Issue by enigmaquip** [jonatkins/ingress-intel-total-conversion#1007]
Info for new mod

{
      "owner": "",
      "name": "SoftBank Ultra Link",
      "rarity": "VERY_RARE",
      "stats": {
        "REMOVAL_STICKINESS": "0",
        "LINK_RANGE_MULTIPLIER": "5000",
        "OUTGOING_LINKS_BONUS": "8",
        "LINK_DEFENSE_BOOST": "1500"
      }

outgoing links stack 100%
link mitigation increased by 50%

**Comment by reckter** [comment]
I think this issue should be closed as this is well implemented now and already 5 month old.
