### ISSUE TITLE
IITC not showing portals in small scale map

### ISSUE THREAD

**Issue by vadimzham** [jonatkins/ingress-intel-total-conversion#1019]
Hi. Tooday i found this bug: IITC not showing portals on small scale map. 
As example:
I picked scale that shows "Links > 2.5km" in standard Intel. It showing links >2.5km AND portals on esges of links > 2.5km.
I picked scale that shows "Links > 2.5km" in IITC.It Shows ONLY links >2.5km without any portals.

**Comment by fkloft** [comment]
This is due to the recent Niantic change. Below a certain zoom level, the server only returns links, but no portals at all. Stock intel then creates dummy portals at the end of the links without actually having any data about them.

This is also implemented in the current test builds of IITC.

**Comment by vadimzham** [comment]
But these dummy portals on the end of links have AJAX lnks on portal information. So, it could be realized in IITC too.

**Comment by flamusdiu** [comment]
Calling the AJAX info will cause extra info from NIA servers -- could result in a ban too.
