### ISSUE TITLE
How COMM entries beyond 50 are fetched?

### ISSUE THREAD

**Issue by fivepointseven** [jonatkins/ingress-intel-total-conversion#1035]
Everytime I refresh chat, I get an array of 50 entries. What happens if ~100 actions occured between refreshes? Is it possible to get all actions?

**Comment by fkloft** [comment]
IITC stores the newest loaded comm entry and will load the *next* 50 actions. If more than 50 happened, the next batch will be loaded on the next refresh.

**Comment by fivepointseven** [comment]
So if, say I have 200 actions per second and refresh comm every second, I will get those 200 in 4 refreshes? Am I getting it right?
