### ISSUE TITLE
Shards known on standard Intel but not on the Artifacts list

### ISSUE THREAD

**Issue by AndOne1974** [jonatkins/ingress-intel-total-conversion#1036]
![shard_known](https://cloud.githubusercontent.com/assets/1571332/9208125/19ad217e-4072-11e5-8891-d974d609686f.png)

It seems that the standard Intel is listing the shard numbers correct but the text on the artifacts list tell us that the info has been removed. Maybe the info is back or where does it come from on the standard Intel?

**Comment by jonatkins** [comment]
Read the last sentence on the artifact list, and look at the portal details panel, just above the resonators.

**Comment by AndOne1974** [comment]
i see concrete "Lightman #27 + #30" and not only "2 Lightman Shards".

**Comment by jonatkins** [comment]
![image](https://cloud.githubusercontent.com/assets/1500194/9210692/99b63fb0-4075-11e5-9d63-9e06c62b4341.png)

**Comment by AndOne1974** [comment]
thx. It would be possible to request the portal details to build the details again, or? oh well, it´s not important if we know where shard are ... some extra clicks if i want to know which shard is where
