### ISSUE TITLE
Nominatim search requires an app key

### ISSUE THREAD

**Issue by max-m** [jonatkins/ingress-intel-total-conversion#1041]
> All Nominatim and Xapi requests require a key starting September 15, 2015. Please visit the MapQuest Developer Network to sign up for an AppKey if you do not have one.
> – [MapQuest Nominatim Search Service Developer's Guide](http://open.mapquestapi.com/nominatim/)

The new request format looks like this:
`http://open.mapquestapi.com/nominatim/v1/search.php?key=YOUR_KEY_HERE&format=json&json_callback=renderBasicSearchNarrative&q=westminster+abbey`

All in all it’s just the new parameter `key`:
```JavaScript
window.NOMINATIM_API_KEY = 'IITC_NOMINATIM_API_KEY';
window.NOMINATIM = '//open.mapquestapi.com/nominatim/v1/search.php?key='+window.NOMINATIM_API_KEY+'&format=json&polygon_geojson=1&q=';
```

**Comment by fkloft** [comment]
Fixed in cb21291a2084053f2b65579cd88392e53f4d5888
