### ISSUE TITLE
Player Tracker not working properly

### ISSUE THREAD

**Issue by intrikit** [jonatkins/ingress-intel-total-conversion#1044]
I checked with both my mobile and desktop test version 0.25. Phone is stock Android 5.1 for mobile, using Chrome version 45.0.2454.99 m for computer. Player tracker worked in former versions but does not now if I downgrade. Some players are tracked but not all. I watched players upgrade a portal and add resonators but they do not appear on my intel map as tracked activity over the past week.  Please help. 
It shows that I was at the location but the other player on the portal does not appear.

**Comment by fkloft** [comment]
player-tracker can only track players based on the public comm log. Actions not logged there cannot be tracked. This includes upgrading resonators.
