### ISSUE TITLE
Unique Highlighter for Visited+Captured

### ISSUE THREAD

**Issue by TLBM** [jonatkins/ingress-intel-total-conversion#1046]
Hi!
I have the problem (PC and Android ) that when I choose highlight Uniques only portals with only "Visited" set are shown in yellow. Portals with "Visited" and "Captured" set are shown in blue. If I unset "Captured" the portal turns yellow.

**Comment by fkloft** [comment]
This is intended behavior.

**Comment by TLBM** [comment]
How would then somebody distinguish between "captured" and portals of the Resistance?

**Comment by fkloft** [comment]
With the highlighter selected, the meaning of the colors is as follows:
- Red: Portal has never been visited or captured by me.
- Yellow: Portal has been visited by me, but not captured.
- Otherwise: Portal has already been captured by me. In this case, the
portal's default color (gray, blue or green) remains.

**Comment by TLBM** [comment]
Thank you for the clarification!
I had not noticed the small difference between orange for neutral and red for not visited.

**Comment by TLBM** [comment]
After reading your color guide I disabled all plugins except "uniques", but the neutral portals are still orange and not gray.

Can you locate the unvisited Portals in the screenshot?
<img width="296" alt="2015-10-04 14_53_56-ingress intel map" src="https://cloud.githubusercontent.com/assets/11824134/10267950/bcd82154-6aa8-11e5-9505-d10df143102e.png">

**Comment by fkloft** [comment]
My bad, neutral portals (also called "gray") are actually orange in IITC
because gray is hard to distinguish on some maps. So again, unvisited
portals are red while visited+captured ones are either blue, green or
orange (="gray") depending on their faction
