### ISSUE TITLE
Map scrapper

### ISSUE THREAD

**Issue by OnkelTem** [jonatkins/ingress-intel-total-conversion#1047]
Recently I found out one neat tool of which you are most likely aware: https://github.com/SummerWish/ingress-exporter

As you probably know it is dead due to:
1) Google wired up their botguard
2) It seems the maintainer abandoned the project

If my understanding is right (I had no chance to try the tool out and can only judge from its description) you could use it for finding portals in a random region. So you first draw a region in IITC, export the geometry to an array, copy-paste to config.cson, rebuild it with `grunt` and run the scrapper:
```
node build/app.js --portals --detail false --new
```
The result was stored in the database for later export and analysis. 

While owning such an information (list of portals) seems to be useful in theory, the usability goes to zero to my mind, as you can't see the portals on the map directly. And I asked myself - why there is no such a scrapper plugin for IITC yet?

Thinking about how it could work lead me to the following scenario. You select a region or just zoom to the level you need, and then run the scrapper. The scrapper is "visiting" system tiles in the region and saves the information to persistent browser storage. After some time (maybe hours — to not arose the bot) when the job is done you start analyzing the collected info. IITC now displays the data both from the server and from the storage, with the priority of online data of course.

What kind of analysis you perform is totally up to you, but even with the existing filters it could be very useful for e.g. highlighting portals you normally don't see at specific zoom levels.

What do you think?

**Comment by fkloft** [comment]
Scrapping data is considered highly TOS violating and won't be supported in IITC.

**Comment by OnkelTem** [comment]
Would you point to where in TOS this is forbidden?

**Comment by PrinterElf** [comment]
https://www.ingress.com/terms
Para 2:
....you shall not:
(d) extract, scrape, or index the Products or Content (including information about users or game play);

**Comment by OnkelTem** [comment]
Thanks @PrinterElf

@fkloft So this is more a matter of interpretation. What IITC is intended for and perfectly does can be treated as extracting, scraping and indexing. There is no *principal* difference between the announced scraper and IITC with its plugins.

**Comment by fkloft** [comment]
You're totally right. IITC is against TOS as well. Be sure to read the FAQ.
Niantic will never give you written proof, but they tolerate IITC, as long
as it doesn't cross borders. Past has shown that Niantic doesn't like any
tools that harvest data. I'd advise you to respect that.

**Comment by flamusdiu** [comment]
IITC primarily displays on the information on the screen and doesn't save
anything elsewhere (by itself). It does cache some portal details when
viewing portals. There is no official plugin that takes information from
the Intel Map and exports it outside of Agent generated information (i.e.
Bookmarks or Draw Tools).

**Comment by OnkelTem** [comment]
My personal view on this (and yours, I believe) is that not only IITC doesn't harm anything — instead it makes the game much funnier. For example, without it I couldn't draw/plan fields (although I've never placed large fields yet) and I most likely abandoned playing long time ago. 

@flamusdiu 
> It does cache some portal details when viewing portals.

Yep, and the similar things that "scrapper" does: it just helps you visit areas of interest, at the zoom level enough to not miss important information. It's like "show me the next (group of) tiles, ok, now the next and etc." — and you repeat it for the area. It also caches the information — of course to save your bandwidth and time.

>  There is no official plugin that takes information from the Intel Map and exports it outside of Agent 
generated information (i.e. Bookmarks or Draw Tools).

On the top of my head I can mention 'link-show-direction' which shows information not available in the official intel map which indeed *may* be treated as violation: it makes reverse engineering of... JSON :)

@fkloft 

Thanks for the explanation.
