### ISSUE TITLE
Feature Request: Mark Missions "Complete" in Missions Plugin

### ISSUE THREAD

**Issue by skipwilson** [jonatkins/ingress-intel-total-conversion#1081]
I'm on the path to Onyx SpecOps, but it's gotten to the point where it's really difficult to figure out the missions that I have NOT done in my area. Would be great if I could mark "complete" in the Missions plugin, which would "hide" the ones I've already completed.

**Comment by llwp** [comment]
concur. would find this feature (particularly mobile version) very useful...

**Comment by fkloft** [comment]
Already implemented. Click on the mission's image

**Comment by skipwilson** [comment]
So not to be ungrateful for what is already implemented (which I had not noticed, and is indeed pretty neat), but marking is not the same thing as hiding. I'm in the NYC Metro area and there are LOTS of missions and mission series around. For instance in Woodlawn Cemetery in the Bronx, there is a 64 mission series. There *are* other missions in that area, but they are drowned out by those 64. So even though I can (and will) mark them all as completed, I still have to wade through a ton of stuff to see what actually remains.

Any chance of using the existing flagging system, and expand it to add a "hide completed missions" checkbox that would filter those out?

Also....would it be cool to make the 'checkmark' in the "mission checked" style stand out a little more? (style plugin-mission-summary.checked::after) It's kinda hard to see now. When I tweaked it out to be white, the contrast was a lot cleaner. Then again the background color call si tout pretty clearly, so no biggy. The filtering is a much bigger deal.
