### ISSUE TITLE
Mod information not available in IITC API?

### ISSUE THREAD

**Issue by n4ru** [jonatkins/ingress-intel-total-conversion#1086]
I'm trying to create a plugin, but I don't see any way to access the mod information on a portal (looking through this page: http://ingress-intel-total-conversion.readthedocs.org/en/latest/core.html#variables)

Short of reading it through jQuery selectors off the screen (obviously unreliable), is there a way to grab it? I thought it would be in window.portals[window.selectedPortal].options.data, but it isn't.

**Comment by felix-kloft** [comment]
It's not, see the

**Comment by fkloft** [comment]
It's not, see the FAQ on the homepage.

**Comment by n4ru** [comment]
I am looking for the mod information for selected portals - not all of them.

**Comment by McBen** [comment]
var details = portalDetail.get(selectedPortal);
  if (details) {
    $.each(details.mods, function(ind, mod) {
      if (mod) { ....

**Comment by ryantheleach** [comment]
Can you close this @n4ru if it's solved?
