### ISSUE TITLE
Question / Request: Unique Plugin Mass Update

### ISSUE THREAD

**Issue by edwinvdpol** [jonatkins/ingress-intel-total-conversion#1088]
Hi,

I don't know if it is allready possible, but is there a way to mass update the portals unique visits and captures without having to click every single portal to update?

Like, in the portal list in view, "Update Uniques" or something? Now I have to click every portal to update the status.

**Comment by fkloft** [comment]
No, because the data required to do so is not available. See FAQ.

**Comment by McBen** [comment]
note: the unique-plugin is able to extract the status from the chat-log too.
