### ISSUE TITLE
Request Keys List Table

### ISSUE THREAD

**Issue by rediguana** [jonatkins/ingress-intel-total-conversion#148]
I've got a feature request for Keys. It would be quite nice if it was possible to display a popup table of keys sorted alphabetically so that they match the order on the Ingress Scanner app. There would also be +/- icons to update the number of keys held in the table, rather than having to visit each portal on the map.

**Comment by nexushoratio** [comment]
With the keys plugin, should this issue be marked closed, or are there additional features to implement?
