### ISSUE TITLE
Plugin to download portal information in CSV

### ISSUE THREAD

**Issue by rediguana** [jonatkins/ingress-intel-total-conversion#170]
Background: _deleted_

It would be great if there was a simple plugin to enable download of all portals in the current view in a simple CSV format. 

All it needs to produce is a csv with the following fields: Name,URL,Latitude,Longitude. These should be included as a header line to prompt GPSBabel.

We just grab the latitude and longitude directly from the portal URL and display it in the [-][d]dd.dddddd format and it works perfectly.

Once the csv is available, it is trivial to convert to KML and GPX using the following command, assuming Portals.csv is the csv, and Portals.gpx and Portals.kml are the desired output formats:

gpsbabel -i unicsv -f Portals.csv -o gpx -F Portals.gpx -o kml -F Portals.kml

At some stage in future it may be possible to include a Description field that contains more information about the portal.

**Comment by ppumkin** [comment]
I think that if there would be an open ingress map where users manually put in data that is outside of the ToC. I think Google just doesnt want ppl hammering the servers with millions of download requests for entire regions, or countries. I mean, if i used something like ViewRanger and put in the portals manually, what do they care. I might as well plot it on a paper map, as long as its manually.
