### ISSUE TITLE
Map: add layers to support diagramming

### ISSUE THREAD

**Issue by rediguana** [jonatkins/ingress-intel-total-conversion#220]
It would be quite useful for link/field planning to have an additional map and layer available.

1. Blank white map layer. It would be very nice to have a blank white map option to enable planning without the distraction of the underlying map.

2. Display portals as neutral. For diagramming, it is sometimes useful to ignore the radius and faction colour of a portal. It would be nice to have a layer option to render all portals at the same size, and perhaps a dark grey or black to contrast against a white map suggested about.

The combination of these would provide a very nice planning tool, that easily can be captured via screenshot, marked up in an editor like photoshop, and then distributed as paper for operatives to use in the field (and without wasting a pile of ink printing satellite maps and the like). This would also translate diagram constructed using IITC to black laser printers, and for photocopying.

**Comment by nexushoratio** [comment]
Neutral markers are available through the Hide portal ownership plugin.

Is a setOpacity() feature still useful?

**Comment by jonatkins** [comment]
there are multiple base maps, some quite subtle so good for making plans while still having reference to the roads, etc
