### ISSUE TITLE
Add option to show portals of certain faction only

### ISSUE THREAD

**Issue by tb527** [jonatkins/ingress-intel-total-conversion#310]
I'd like to see a layer option to show only portals belonging to the faction you'd like to see. For example, if I'm planning a route to fill in missing resonators for the extra 250 AP each, then I only want to see friendly portals in the portals missing resonators view. Obviously I can't fill in missing resonators in enemy portals, and a lot of the time I'm not trying to capture them, so it would be better for me to have enemy portals hidden completely from this view since they clutter the map in high density areas. But this feature would be useful for other purposes also, so I'd like to see a global layer option to individually toggle enemy portals from view, and another one for friendly portals.

**Comment by nexushoratio** [comment]
This is implemented, correct?
