### ISSUE TITLE
AP List effective energy.

### ISSUE THREAD

**Issue by Mytharox** [jonatkins/ingress-intel-total-conversion#361]
To calculate effective energy in the AP List (in your last test build)

return shieldsEffect;

should probably be

return 1/shieldsEffect;

otherwise more shields make the portal weaker.

--

Also adding the effect of links might be nice:

  var effectOfShields = plugin.apList.getShieldsEffect(portal);
to
 var effectOfShields = plugin.apList.getShieldsEffect(portal);
  var effectOfLinks = plugin.apList.getLinksEffect(portal);

and adding it here:

effectiveEnergy = resosStats.currentEnergy * effectOfLinks * effectOfShields * effectOfResoDistance;

and I guess something like:

window.plugin.apList.getLinksEffect = function(portal) {
  // using the leaked link defense formula - http://i1.wp.com/decodeingress.me/wp-content/uploads/2013/04/wpid-links_03.png
  var linkCount = portal.portalV2.linkedEdges ? portal.portalV2.linkedEdges.length : 0;
  var linksEffect = 0;
	switch (linkCount)
	{
	case 0:
		linksEffect = 0;
		break;
	case 1:
		linksEffect = 10;
		break;
	case 2:
		linksEffect = 19;
		break;
	case 3:
		linksEffect = 28;
		break;
	case 4:
		linksEffect = 37;
		break;
	case 5:
		linksEffect = 42;
		break;
	case 6:
		linksEffect = 44;
		break;
	case 7:
		linksEffect = 47;
		break;	
	case 8:
		linksEffect = 48;
		break;	
	case 9:
		linksEffect = 49;
		break;			
	default: // anything over 9
		linksEffect = 50;
		break;
	}
	linksEffect = 1 / (1 - linksEffect / 100)
  return linksEffect;
}

and ofcourse to display it:

window.plugin.apList.getPortalEffectiveLvTitle = function(portal) {
  var t = 'Effective energy:\t' + portal.effectiveLevel.effectiveEnergy + '\n'
        + 'Effect of Shields:\t' + portal.effectiveLevel.effectOfShields + '\n'
        + 'Effect of resos dist:\t' + portal.effectiveLevel.effectOfResoDistance + '\n'
        + 'Origin Level:\t' + portal.effectiveLevel.originLevel;
  return t;
}

to

window.plugin.apList.getPortalEffectiveLvTitle = function(portal) {
  var t = 'Effective energy:\t' + portal.effectiveLevel.effectiveEnergy + '\n'
        + 'Effect of Shields:\t' + portal.effectiveLevel.effectOfShields + '\n'
		+ 'Effect of Links:\t' + portal.effectiveLevel.effectOfLinks + '\n'
        + 'Effect of resos dist:\t' + portal.effectiveLevel.effectOfResoDistance + '\n'
        + 'Origin Level:\t' + portal.effectiveLevel.originLevel;
  return t;
}

*updated code 11-6-2013

**Comment by nexushoratio** [comment]
I believe that all calculations are currently correct.  This could probably be closed.
