### ISSUE TITLE
Integrate Keys with Portal List

### ISSUE THREAD

**Issue by bobpaul** [jonatkins/ingress-intel-total-conversion#372]
It would be really great if the Portal List plugin had a column for keys so everything could be managed on 1 list.

Even better if portal list also had a "Distance" column so you can define a map location (or on mobile, it knows where you are) and then sort the portal list just like your keys are sorted (by distance from you).

**Comment by nexushoratio** [comment]
Keys are integrated with Portal List now.

I imagine the desire to sort by Distance would be to allow one to quickly scan both through the Portal List and the scanner to match up key counts.   Since the scanner can now sort by title as well, maybe that part of the request is not needed now?

**Comment by jonatkins** [comment]
I've been considering a separate 'portal distance' plugin for a while. This would allow a user to set their location manually (or detect from GPS on mobile, and maybe browser location APIs), then show this distance in the portal details and add it to portal list. This would be separate from keys or portals-list plugins though
