### ISSUE TITLE
Drawn plugin ranges

### ISSUE THREAD

**Issue by MonoTovarisj** [jonatkins/ingress-intel-total-conversion#382]
I have drawn 2 circles with approximately the same size, to see how long I can make a link, however because of the drawn circles not being the same, however because of the earths curvature, the circles are not an exact tool for checking distances.

As you can see in the picture I would be able to make a link from iceland to poland but not from poland to iceland.

So drawing a circle on earth would not be visualized as a circle on the map.

![drawn bug](https://f.cloud.github.com/assets/3660683/659491/6ef33be8-d69b-11e2-82cc-51e2022407f3.png)

**Comment by nexushoratio** [comment]
It looks like this functions properly these days.
