### ISSUE TITLE
Reopened: "Highlight portals you can upgrade" plugin enhancements

### ISSUE THREAD

**Issue by tb527** [jonatkins/ingress-intel-total-conversion#385]
I thought I had found a bug in "Highlight portals you can upgrade to a specific level" but it didn't hold up. I am reopening this issue because there are some ideas for enhancements to the "Highlight portals you can upgrade" plugin listed in the comments below that I think are worth taking a look at.

**Comment by nexushoratio** [comment]
I believe that improvements had been made to this highlighter.  Not that it matters since this information is no longer readily available and this highlighter is currently retired.

This issue can probably be marked closed.
