### ISSUE TITLE
Portal parameters (hack speed, multihack, attack)

### ISSUE THREAD

**Issue by sorgo** [jonatkins/ingress-intel-total-conversion#410]
I would like to add to portal detail data about these parametres:
* hack speed in seconds between two hacks
* total number of hacks possible until burnout
* total max time worth staying at portal (hack speed * nr of hacks)
* turret & force amp attack intensity (only RARE items are around, haven't seen any T or FA of C or VR rarity)

**UPDATE: The the HS and MH MODs are orderer by rarity DESC, so the most rare mod has always a full value and the rest 0.5, [1.0, 0.5, 0.5, 0.5];**
Proven by field tests, the values we got are all here in "excel".
https://docs.google.com/spreadsheet/ccc?key=0AtBPyzAvlFORdC1kemN0YU9MSS1UMmhDbWtBb090ZUE&usp=sharing

**Comment by nexushoratio** [comment]
I think everything in this issue has been implemented.

**Comment by jonatkins** [comment]
Force amps/turrets could have the totals displayed as well, so will leave open

**Comment by nexushoratio** [comment]
Ahh OK.  You get the values when hovering.  I wasn't sure there would be enough room to put them in that block.  Pretty crowded as is.

**Comment by fkloft** [comment]
Values for individual mods are included in their tool tip, the values for force amplifier, hit bonus and attack frequency are now included in the general info block below as well.
