### ISSUE TITLE
Effective level in AP List plugin applies shield mitigation backwards

### ISSUE THREAD

**Issue by lablua** [jonatkins/ingress-intel-total-conversion#449]
getEffectiveLevel() in the current release version AP list plugin is applying shields backwards. Stronger shields make the effective level go down, weaker shields make it go up. getShieldsEffect() is returning the fraction of damage that passes through the shields. (.9 for 1 common, .7 for 1 VR, etc) getEffectiveLevel() is then directly multiplying this by the current energy to get effective energy, instead of using 1/getShieldsEffect()

**Comment by nexushoratio** [comment]
This issue could probably be closed.
