### ISSUE TITLE
Suggestion: Show ETA for decay in Tooltips

### ISSUE THREAD

**Issue by yoshimo** [jonatkins/ingress-intel-total-conversion#455]
Every 24h a resonator looses a small amount of energy, so it would be nice if the mouse over tooltips for portals, resonators and maybe links would show how long it will take until they are decayed.
So if the next drain will kill it you can ask for help, or the other way round, tell your people that it is important to not recharge them, if you want to get rid of some misplaced things.

**Comment by nexushoratio** [comment]
Is there anything of interest in this issue that could still be implemented?
