### ISSUE TITLE
Sync is displaying red, authorize button greyed out

### ISSUE THREAD

**Issue by tyrope** [jonatkins/ingress-intel-total-conversion#476]
See http://img850.imageshack.us/img850/9962/rv4i.png

**Comment by wschoot** [comment]
I'm having the exact same, but cannot resolve it myself. It's only on mobile, desktop works fine. IITC 20170430. I'll try non-test now.

**Comment by whartyENL** [comment]
I'm having the same issue on android mobile. Used to work and stopped about a week ago. Have uninstalled/reinstalled both plugin and iitc but still no luck

**Comment by wschoot** [comment]
The workaround (advanced settings => fake user agent) still works
