### ISSUE TITLE
Highlight Imminent Decay

### ISSUE THREAD

**Issue by tb527** [jonatkins/ingress-intel-total-conversion#481]
I suggested this a week and a half ago in a comment in a separate issue, but since then the area I help control has increased by several dozen portals so I need this plugin now since I simply don't have the xm to recharge everything. 

Basically the idea is to highlight with red every portal that has at least one resonator equal to or under 15% (i.e. will decay completely within 24 hours), highlight with orange portals with at least one resonator at or below 30%, and highlight with yellow portals with at least one resonator at or below 45%. This would be a significantly different function than the highlight portals that need recharge highlighter.

**Comment by nexushoratio** [comment]
This plug is implemented and this issue can probably be marked closed.
