### ISSUE TITLE
Show resonator upgrade time and/or highlight portal which had it's resonator recently upgraded.

### ISSUE THREAD

**Issue by ingress-agent** [jonatkins/ingress-intel-total-conversion#489]
Show reso upgrade time on both enemy & friendly portals. I know this is not yet implemented into Ingress intel itself. But I guess for now what the developer can do is, from the last load of portal info on intel page till next update of intel page, if any portal had a reso upgrade, highlight it and/or show time of upgrade.

**Comment by nexushoratio** [comment]
Time to close this issue?
