### ISSUE TITLE
New plugins submitted off Github - dev utils, highlighter for invalid resonator/mod counts

### ISSUE THREAD

**Issue by jonatkins** [jonatkins/ingress-intel-total-conversion#516]
I have written two plugins for IITC for my own use and thought that I should share them with the other users and developers.

The first one is developer plugin that adds a link to the portal details and shows the raw JSON data for the portal and the links and fields at the selected portal. That was just a little helper script to see which data is available.
Find it at:
http://studiy.tu-cottbus.de/~fhaefner/IITC_plugin-_Raw_Portal_Data.tamper.js

The second is a highlighter plugin. It highlights portals which are violating the resonator rule (exceeding the maximal number of resonators for the resonator level by a single person) in yellow and portals violating the new mod rule (exceeding the maximal number of mods by one person) in magenta. If both rules are violated it colors the portal in red.
Find it at:
http://studiy.tu-cottbus.de/~fhaefner/IITC_plugin-_highlight_portals_with_violated_resonator-mod_rule.tamper.js

Maybe you can make good use of it or even improve them.
I am sorry to share them that way but I am not familiar with git.

**Comment by nexushoratio** [comment]
Time to close this issue?
