### ISSUE TITLE
Relative Portal Highlighters

### ISSUE THREAD

**Issue by vita10gy** [jonatkins/ingress-intel-total-conversion#554]
None of the relative portal highlighters work anymore. I took a stab at it, but my brain is officially mush.  Maybe it will be obvious to people that know more about what's going with the new loading.

The issues is that the relative highlighters shade the portals based on the value of every other portal. (So for example, the portal worth the most AP is the brightest, and the portal worth the least AP is the dimmest.)

However, as it stands, portals are marked to highlight as they're loaded/drawn. They used to redraw as batches were loaded, but no longer.

**Comment by nexushoratio** [comment]
I think this issue can be closed.
