### ISSUE TITLE
Long links not represented the same as stock intel

### ISSUE THREAD

**Issue by gnarf** [jonatkins/ingress-intel-total-conversion#629]
This was brought to my attention: http://jsbin.com/ifIFafU/1/edit?html,css,output

This point is in the middle of a ~900km link currently residing in Alaska.

The screenshot shows both stock intel and IITC (with the red line added by another plugin).  There seems to be an error of a few meters near the center if you lay them on top of each other.

I've heard that the approximations from https://github.com/springmeyer/arc.js are more accurate however I haven't had a chance to test them.

**Comment by nexushoratio** [comment]
I know a lot of work went into improving the drawing of links.  Is there anything else to be done for this particular issue?
