### ISSUE TITLE
Sync not working with Keys and Uniques

### ISSUE THREAD

**Issue by joselsegura** [jonatkins/ingress-intel-total-conversion#862]
Related with #745 

I had deleted all my sync information from local storage and Drive. I restored from a file my bookmarks, start to fill "captured" portals (for Uniques) and put some keys.

I got no sync between devices/browsers, except for Bookmarks, that works fine.

In Google Drive, in my IITC-SYNC-DATA-V2 folder I have a bookmarks file, that seems to be updated each time I change my bookmarks, and a "uniques" file, that seems only to be created and never changed anymore. I don't have any file for keys.

**Comment by JoseLSegura** [comment]
Now it works, but it seems that I've lost all my uniques information, but not my old keys information (I was not using it since a while due to it doesn't sync).

Is there any possibility of restoring my uniques information???
