### ISSUE TITLE
Include GMail Address in PLAYER hash

### ISSUE THREAD

**Issue by slow23** [jonatkins/ingress-intel-total-conversion#925]
I wanted to use IITC to verify users via a plugin. But since IITC rewrites the whole document, there's no way to get the player's mail.

With one simple line of code, the mail can be added to the PLAYER hash, to be used in other plugins.

<code>if(document.getElementById('header_email')) window.PLAYER['mail']=document.getElementById('header_email').innerHTML;</code>

**Comment by jonatkins** [comment]
You couldn't rely on such data in plugins - a hacker could easily rewrite the PLAYER hash (e.g. another plugin) to supply bogus agent name and/or email.

Agent verification is an issue, but without an official API providing such a feature to developers I can't see a way of doing it safely/reliably.

**Comment by slow23** [comment]
Ok, you got a point there. Then there's the good old RL handshake for now!
