### ISSUE TITLE
Strongest VR shield known to man!

### ISSUE THREAD

**Issue by nh-99** [jonatkins/ingress-intel-total-conversion#938]
So I am pretty sure this is a bug... I really hope it is, wouldn't want to be the one that has to blow this off.

![strong shield](https://cloud.githubusercontent.com/assets/3317164/6032893/b976689e-abdc-11e4-9fb2-315fc5bb5a85.PNG)

**Comment by nh-99** [comment]
Odd... it's only showing that on this one portal...

**Comment by neon-ninja** [comment]
Can you post a portal link please?

**Comment by jonatkins** [comment]
If it is a bug, I'm pretty certain it's in Ingress backend, not IITC. 

The servers just return a list of stats for mods. IITC does some basic formatting for display, but only for stats that need it. Shield stats are displayed as returned from the server.

For example, the raw data for shields is usually in this form:

```json
      [
        "agent_name",
        "Portal Shield",
        "COMMON",
        {
          "REMOVAL_STICKINESS": "20",
          "MITIGATION": "30"
        }
      ],
```

**Comment by nh-99** [comment]
Yup, the stickiness values seem to have changed. New data rolling out, no official confirmation yet.

**Comment by jonatkins** [comment]
We're extremely unlikely to ever hear any confirmation/explanation from Niatnic on this - it's an internal stat that's only visible with ToS breaking tools like IITC.

I've made an intelligent guess that these new high values can be treated as a percentage, as is done for some other mod stats - commit b029da632f99b5170c86a776416f04512e3e288d
