### ISSUE TITLE
L0 Portals are showing up on big maps?

### ISSUE THREAD

**Issue by rddaz2013** [jonatkins/ingress-intel-total-conversion#949]
Sometimes uncaptured Portals could be seen on the map but only higher L5+ portal should ..

**Comment by enigmaquip** [comment]
This is because of the changes that niantic is making for missions. I'm betting that a mission starts at those neutral portals if you check

**Comment by jonatkins** [comment]
Yes - the backend servers are returning portals below the level selected by the user. IITC renders all portals sent to it (but the stock site doesn't, it seems), hence the difference.

As, currently, this causes an excessive amount of additional data to be returned to the browser by the servers (to both IITC and stock intel) when viewing continent/global levels, I expect Niantic will realise their error and change it back to the old behaviour.

For now, I'm doing nothing - I'll wait for the stock site to stabilize then see what, if anything, needs to change in IITC.

**Comment by jonatkins** [comment]
This community post has more discussion related to this
https://plus.google.com/112077625695139477102/posts/aaYguVdQC1s

**Comment by jonatkins** [comment]
niantic finished the missions on stock intel and this was still an issue, so fixed in iitc, c5b068eda1ed35db7384e6080da024d5e58f4a88
