### ISSUE TITLE
IITC / Safari / Tampermonkey - hangs in Loading Data...

### ISSUE THREAD

**Issue by pleasantone** [jonatkins/ingress-intel-total-conversion#954]
Long and short, it should work, it doesn't most of the time. I'm sorry, this is a super crappy bug report, I'm happy to report back any debugging possible.

Safari 8.0.3 / OS X Yosemite - desktop - not iOS
Tampermonkey
Just the IITC main download, no other plugins active, both 0.22.0 and 0.22.1.20150308... fail in the same way 90% of the time, but do work correctly occasionally.  It hangs in Loading Data, black screen, initial elements never replaced.

Why, do you ask, am I doing this under Safari instead of Chrome? Because of other ingress related stuff that (strangely) works in Safari but not Chrome.

![screen shot 2015-03-08 at 12 25 08 pm](https://cloud.githubusercontent.com/assets/5339793/6547190/42cda2e0-c58e-11e4-9f7a-d6b2d898e232.png)

**Comment by jonatkins** [comment]
Which version of Tampermonkey? I had the same issue recently on Chrome which was due to a Tampermonkey bug. 

If I remember correctly it was 3.11.4595 that was broken, and then fixed in 3.11.4600

**Comment by pleasantone** [comment]
You  nailed it. 4595. Thank you and sorry.
