### ISSUE TITLE
Please add small S2 cells borders as new plugin or in regions.user.js

### ISSUE THREAD

**Issue by nsauk** [jonatkins/ingress-intel-total-conversion#956]
For experiments with MU density it would be nice to see [these map](https://iitc.caconym.org/cells/) directly into the IITC. Looks like it's easy to make on the basis of regions.user.js, but I could not.

**Comment by JensenDied** [comment]
That site basically uses the regions.js plugin with very small changes to enable going up to higher S2 cell levels (smaller area).

**Comment by jonatkins** [comment]
there's no general use for smaller S2 cells, so not going to accept it as a plugin
