### ISSUE TITLE
Question: Is there a standard(ish) way of creating user interface elements in plugins?

### ISSUE THREAD

**Issue by MarkTraceur** [jonatkins/ingress-intel-total-conversion#957]
I looked at the portal list plugin for an example, and it looks like it uses manually-constructed HTML strings. Any way I can be less 1999 in the plugin I plan to write?

**Comment by fkloft** [comment]
The portal list doesn't use HTML string manipulation but the DOM API, which is the native way to manipulate HTML documents from JavaScript. You can either use this, or jQuery or HTML string manipulation (which I wouldn't recommend either). jQuery UI is included as well, but it lacks lots of CSS from the original theme, you may need to included your own styles.

**Comment by MarkTraceur** [comment]
@fkloft so nothing standard for creating dialogs, handling events, buttons, etc.? Seems rather caveman.

**Comment by fkloft** [comment]
For dialogs, there is a framework around jQuery UI's dialog widget, look at code/dialog.js
Events: use DOM or jQuery, whatever suits your needs. JQuery has issues if you create and remove elements and don't remove the event handlers.
Buttons: HTML has buttons. What else are you looking for?

**Comment by MarkTraceur** [comment]
OK, good enough I guess. Thanks.
