### ISSUE TITLE
Browserless use of IITC?

### ISSUE THREAD

**Issue by Logikz** [jonatkins/ingress-intel-total-conversion#958]
I'm trying to see if it's possible to integrate parts of iitc for use with a slack integration.  I'm a developer, but new to web stuff.  I'm not even sure how to go about doing that, would the slack integration need its own ingress account, then you mimic a login via javascript and call iitc functions from there?

Could you just call the scanner API without logging into the intel map?

Mainly, I'm just trying to see if there's an easy way to check the status of portals located at various common farm areas, although there could be lots of fun other uses.

Thanks

**Comment by nexushoratio** [comment]
Sounds like everything you are proposing are strictly against the Ingress Terms of Service.

**Comment by jonatkins** [comment]
The IITC project is strictly a replacement user interface within the web browser environment.
