### ISSUE TITLE
Canvas rendering breaks link direction

### ISSUE THREAD

**Issue by ckanoab** [jonatkins/ingress-intel-total-conversion#959]
If the canvas rendering plugin is installed the show link direction plugin breaks. The option panel is still there but regardless of what you choose, no direction is indicated. Disabling canvas render fixes the issue.

**Comment by jonatkins** [comment]
they're known to not be compatible. no fix is practical

**Comment by ckanoab** [comment]
not able to find where the drawing changes with canvas plugin, but could something like this be used to get some functionality? https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineDashOffset
