### ISSUE TITLE
dumb canvas rendering question

### ISSUE THREAD

**Issue by pleasantone** [jonatkins/ingress-intel-total-conversion#974]
Not an issue, per-se.

I've got some changes to the cross-links plugin to create a second polygon in crossLinks.showLink that acts as a "highlighter" around a cross link, and it renders beautifully in SVG, but in canvas rendering, it's a bit of a mess.

I'm creating the second line with:
       color: highlight_color,
       opacity: 0.3,
       weight: 50,
       clickable: false,
       dashArray: [8,8],
       guid: link.options.guid

Is there any other magic I need for canvas to get the line to show with rounded corners and a dashed line?

**Comment by fkloft** [comment]
Canvas rendering does not support dashed lines, a known issue.

**Comment by pleasantone** [comment]
thank you
