### ISSUE TITLE
Currently i get xx % loaded 1-7 failed on android 4.4.2 galaxy tab4

### ISSUE THREAD

**Issue by grzchr15** [jonatkins/ingress-intel-total-conversion#995]
I want to help debug, But how to find reson of failed partiell request. .
it happen on stock iitc and Chrome. 
f12 network inspector  shows  no http request with Problems. All http Status 200
Alogcat shows also no related messages.

**Comment by grzchr15** [comment]
13:02:47.630 WARN iitcm-console
<script/total-conversion-build.user.js>:14692: getEntities status: 1 tiles: 0 successful, 1 failed. delay 10 seconds

**Comment by grzchr15** [comment]
13:02:47.630 WARN iitcm-console
script/total-conversion-build.user.js:14692: getEntities status: 1 tiles: 0 successful, 1 failed. delay 10 seconds

**Comment by grzchr15** [comment]
13:05:19.316 WARN iitcm-console
script/total-conversion-build.user.js:14692: getEntities status: 2 tiles: 0 successful, 2 failed. delay 10 seconds

**Comment by pleasantone** [comment]
Yes, I'm seeing the same thing. Is the JSON decoding of the returned data failing?

Authors? This is beyond my minimal javascript skills so far.

**Comment by jonatkins** [comment]
the backend servers started returning empty responses. latest version now treats these as errors and retries.
