### ISSUE TITLE
uncaught TypeError: a.taget.className.indexOf is not a function

### ISSUE THREAD

**Issue by pleasantone** [jonatkins/ingress-intel-total-conversion#997]
I think it's happening in the bookmarks function, but even with all plugins disabled, I'll sometimes get
uncaught TypeError: object is not a function.

I'm not asking for you to fix this, I'm asking for guidance on debugging. Is there a developers forum outside of issues?

![screen shot 2015-05-13 at 4 34 00 pm](https://cloud.githubusercontent.com/assets/5339793/7623333/e65acdb0-f98d-11e4-8c2c-878fee998967.png)

**Comment by jonatkins** [comment]
The exception is in gen_dashboard.js - part of stock intel.

There's something they do - probably as part of the 'botguard' protection, that causes an exception to be thrown on the first link clicked after a page load. Not much we can do about this really...
